function Housing_Price = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HOUSING_PRICE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  HOUSING_PRICE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Housing_Price = importfile("/Users/simranmalhotra/Documents/MATLAB/machine-learning-ex/ex1/ex1data2.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Apr-2020 12:54:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Size_of_House", "No_of_bedrooms", "Price"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Housing_Price = readtable(filename, opts);

end